package com.example.flightbooking.service;

import com.example.flightbooking.model.Country;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;

@Service
public class CountryService {

    public List<Country> getCountries() {
        Country alb = new Country("Albania");
        Country and = new Country("Andorra");
        Country arm = new Country("Armenia");
        Country aut = new Country("Austria");
        Country aze = new Country("Azerbaijan");
        Country blr = new Country("Belarus");
        Country bel = new Country("Belgium");
        Country BiH = new Country("Bosnia and Herzegovina");
        Country bg = new Country("Bulgaria");
        Country hrv = new Country("Croatia");
        Country cyp = new Country("Cyprus");
        Country cze = new Country("Czech Republic");
        Country dnk = new Country("Dennmark");
        Country est = new Country("Estonia");
        Country fin = new Country("Finland");
        Country fr = new Country("France");
        Country geo = new Country("Georgia");
        Country de = new Country("Germany");
        Country grc = new Country("Greece");
        Country hun = new Country("Hungary");
        Country isl = new Country("Iceland");
        Country irl = new Country("Ireland");
        Country ita = new Country("Italy");
        Country rks = new Country("Kosovo");
        Country lva = new Country("Latvia");
        Country lie = new Country("Liechtenstein");
        Country ltu = new Country("Lithuania");
        Country lux = new Country("Luxembourg");
        Country mlt = new Country("Malta");
        Country md = new Country("Moldova");
        Country mco = new Country("Monaco");
        Country mne = new Country("Montenegro");
        Country nrl = new Country("Netherlands");
        Country nmk = new Country("North Macedonia");
        Country nor = new Country("Norway");
        Country pol = new Country("Poland");
        Country prt = new Country("Portugal");
        Country rou = new Country("Romania");
        Country rus = new Country("Russia");
        Country srb = new Country("Serbia");
        Country sk = new Country("Slovakia");
        Country slo = new Country("Slovenia");
        Country esp = new Country("Spain");
        Country swe = new Country("Sweden");
        Country tur = new Country("Turkey");
        Country ukr = new Country("Ukraine");
        Country uk = new Country("United Kingdom");
        ArrayList<Country> countries = new ArrayList<>();
        countries.add(alb);
        countries.add(and);
        countries.add(arm);
        countries.add(aze);
        countries.add(aut);
        countries.add(blr);
        countries.add(bel);
        countries.add(BiH);
        countries.add(bg);
        countries.add(hrv);
        countries.add(cyp);
        countries.add(cze);
        countries.add(dnk);
        countries.add(est);
        countries.add(fin);
        countries.add(fr);
        countries.add(geo);
        countries.add(de);
        countries.add(grc);
        countries.add(hun);
        countries.add(isl);
        countries.add(irl);
        countries.add(ita);
        countries.add(rks);
        countries.add(lva);
        countries.add(lie);
        countries.add(ltu);
        countries.add(lux);
        countries.add(mlt);
        countries.add(md);
        countries.add(mco);
        countries.add(mne);
        countries.add(nrl);
        countries.add(nor);
        countries.add(nmk);
        countries.add(pol);
        countries.add(prt);
        countries.add(rou);
        countries.add(rus);
        countries.add(srb);
        countries.add(sk);
        countries.add(slo);
        countries.add(esp);
        countries.add(swe);
        countries.add(tur);
        countries.add(ukr);
        countries.add(uk);
        return countries;
    }
}
